server: 
  port: 8082
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/eleMonitor?useSSL=false&serverTimezone=UTC
    username: root #用户名
    password: root
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  
logging:
  file: ./logs/eleMonitor.log